import { Category, Feature, Listing } from "@/lib/types";

export const categories: Category[] = [
  {
    id: "auto",
    label: "Автомобили",
    caption: "Новые и с пробегом",
    icon: "🚗",
    listingCount: "13 540 объявлений",
  },
  {
    id: "electronics",
    label: "Электроника",
    caption: "Смартфоны, ноутбуки, гаджеты",
    icon: "📱",
    listingCount: "9 870 объявлений",
  },
  {
    id: "real_estate",
    label: "Недвижимость",
    caption: "Квартиры, дома, коммерция",
    icon: "🏠",
    listingCount: "7 210 объявлений",
  },
  {
    id: "services",
    label: "Услуги",
    caption: "Ремонт, обучение, помощь",
    icon: "🛠️",
    listingCount: "6 420 объявлений",
  },
];

export const popularListings: Listing[] = [
  {
    id: "1",
    listingSaleMode: "auction",
    title: "Toyota Camry 2020, 2.5 AT, один владелец",
    price: "2 490 000 ₽",
    priceValue: 2490000,
    location: "Москва",
    publishedAt: "Сегодня",
    postedAtIso: "2026-04-20T10:20:00+03:00",
    category: "auto",
    image: "from-zinc-700 via-slate-500 to-slate-300",
    condition: "Пробег 62 000 км",
    description:
      "Автомобиль в отличном состоянии, обслуживался у официального дилера. Без ДТП, кузов в родной краске. Комплектация с камерой заднего вида и подогревами.",
    sellerName: "Алексей",
    sellerPhone: "+7 (901) 123-45-67",
  },
  {
    id: "2",
    listingSaleMode: "auction",
    title: "iPhone 15 Pro 256GB, Natural Titanium",
    price: "94 500 ₽",
    priceValue: 94500,
    location: "Санкт-Петербург",
    publishedAt: "2 часа назад",
    postedAtIso: "2026-04-20T13:05:00+03:00",
    category: "electronics",
    image: "from-slate-600 via-zinc-400 to-slate-100",
    condition: "Идеальное состояние",
    description:
      "Телефон без царапин и сколов, аккумулятор 98%. Полный комплект: коробка, кабель, чек. Использовался в чехле и с защитным стеклом.",
    sellerName: "Марина",
    sellerPhone: "+7 (921) 210-88-19",
  },
  {
    id: "3",
    title: "2-к квартира, 56 м², рядом с метро",
    price: "11 900 000 ₽",
    priceValue: 11900000,
    location: "Казань",
    publishedAt: "Вчера",
    postedAtIso: "2026-04-19T15:30:00+03:00",
    category: "real_estate",
    image: "from-cyan-800 via-sky-500 to-sky-100",
    condition: "Современный ремонт",
    description:
      "Светлая квартира на 8 этаже, кухня-гостиная и отдельная спальня. До метро 7 минут пешком. Остается встроенная техника и мебель.",
    sellerName: "Ильдар",
    sellerPhone: "+7 (987) 654-33-21",
  },
  {
    id: "4",
    title: "Сборка мебели и мелкий бытовой ремонт",
    price: "от 1 500 ₽",
    priceValue: 1500,
    location: "Екатеринбург",
    publishedAt: "4 часа назад",
    postedAtIso: "2026-04-20T11:40:00+03:00",
    category: "services",
    image: "from-amber-700 via-orange-500 to-amber-100",
    condition: "Выезд в день обращения",
    description:
      "Собираю шкафы, кухни, кровати и другую мебель. Также выполняю мелкий ремонт: навес полок, карнизов, замена фурнитуры. Работаю аккуратно и по договоренности.",
    sellerName: "Сергей",
    sellerPhone: "+7 (912) 005-44-78",
  },
  {
    id: "5",
    listingSaleMode: "auction",
    title: "MacBook Air M2, 16/512, гарантия до 2027",
    price: "129 000 ₽",
    priceValue: 129000,
    location: "Новосибирск",
    publishedAt: "Сегодня",
    postedAtIso: "2026-04-20T09:00:00+03:00",
    category: "electronics",
    image: "from-slate-800 via-slate-600 to-slate-200",
    condition: "Как новый, полный комплект",
    description:
      "Ноутбук в состоянии нового, использовался дома для работы с документами. Русская раскладка, цикл батареи 42. Есть чек и официальная гарантия.",
    sellerName: "Егор",
    sellerPhone: "+7 (913) 444-77-56",
  },
  {
    id: "6",
    title: "Аренда студии 28 м² в новом ЖК",
    price: "39 000 ₽ / мес",
    priceValue: 39000,
    location: "Краснодар",
    publishedAt: "1 день назад",
    postedAtIso: "2026-04-19T18:15:00+03:00",
    category: "real_estate",
    image: "from-indigo-700 via-blue-500 to-sky-100",
    condition: "Без комиссии",
    description:
      "Студия с новым ремонтом и техникой, никто не жил. Закрытый двор, рядом остановка и супермаркет. Сдается на длительный срок.",
    sellerName: "Ольга",
    sellerPhone: "+7 (918) 000-11-12",
  },
  {
    id: "7",
    listingSaleMode: "auction",
    title: "Volkswagen Tiguan 2019, полный привод",
    price: "2 150 000 ₽",
    priceValue: 2150000,
    location: "Нижний Новгород",
    publishedAt: "3 часа назад",
    postedAtIso: "2026-04-20T12:35:00+03:00",
    category: "auto",
    image: "from-slate-900 via-slate-700 to-slate-300",
    condition: "Пробег 84 000 км",
    description:
      "Оригинальный ПТС, два ключа, без технических проблем. Полный привод, климат-контроль, камера и парктроники. Торг у капота.",
    sellerName: "Денис",
    sellerPhone: "+7 (952) 777-44-00",
  },
  {
    id: "8",
    listingSaleMode: "auction",
    title: "PlayStation 5 Slim + 2 геймпада",
    price: "54 000 ₽",
    priceValue: 54000,
    location: "Москва",
    publishedAt: "Сегодня",
    postedAtIso: "2026-04-20T08:10:00+03:00",
    category: "electronics",
    image: "from-indigo-900 via-blue-700 to-cyan-200",
    condition: "Чек и гарантия",
    description:
      "Приставка в отличном состоянии, тихая и чистая. В комплекте второй геймпад и зарядная станция. Продаю из-за редкого использования.",
    sellerName: "Роман",
    sellerPhone: "+7 (916) 301-22-90",
  },
  {
    id: "9",
    title: "Репетитор по английскому для взрослых",
    price: "2 000 ₽ / урок",
    priceValue: 2000,
    location: "Казань",
    publishedAt: "Вчера",
    postedAtIso: "2026-04-19T12:00:00+03:00",
    category: "services",
    image: "from-emerald-800 via-teal-500 to-emerald-100",
    condition: "Онлайн и офлайн",
    description:
      "Провожу индивидуальные занятия с упором на разговорную практику и работу. Есть программы для подготовки к собеседованиям и переезду.",
    sellerName: "Алина",
    sellerPhone: "+7 (927) 111-60-61",
  },
  {
    id: "10",
    listingSaleMode: "auction",
    title: "3-к квартира, 82 м², парк через дорогу",
    price: "16 400 000 ₽",
    priceValue: 16400000,
    location: "Санкт-Петербург",
    publishedAt: "5 часов назад",
    postedAtIso: "2026-04-20T10:45:00+03:00",
    category: "real_estate",
    image: "from-cyan-900 via-blue-600 to-sky-100",
    condition: "Кухня-гостиная, 2 санузла",
    description:
      "Просторная семейная квартира в доме 2021 года. Панорамные окна, теплые полы в санузлах, подземный паркинг. До центра 20 минут на метро.",
    sellerName: "Никита",
    sellerPhone: "+7 (911) 402-32-77",
  },
];

export const features: Feature[] = [
  {
    title: "Публикация за 2 минуты",
    description: "Короткая форма, понятные поля и быстрое размещение без сложностей.",
    icon: "⚡",
  },
  {
    title: "Поиск, который экономит время",
    description: "Точный запрос, фильтры и подсказки помогают быстрее находить нужное.",
    icon: "🔎",
  },
  {
    title: "Безопасные сделки и профиль",
    description: "Проверенные продавцы, история и репутация в одном понятном интерфейсе.",
    icon: "🛡️",
  },
];
